import {test,expect} from '@playwright/test';

test('sample, real worker retrieval, CRUD, snapshot, persistence and export',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));const requests:string[]=[];page.on('request',r=>requests.push(r.url()));
 await page.goto('/');await expect(page.getByRole('button',{name:'Run turn 3',exact:true})).toBeDisabled();await expect(page.locator('.turn')).toHaveCount(10);await expect(page.locator('.doc-item')).toHaveCount(10);
 await page.getByRole('button',{name:'Index documents',exact:true}).click();await expect(page.getByText('Index ready',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Run turn 3',exact:true}).click();await expect(page.locator('.method-column.raw .result-card')).toHaveCount(5);await expect(page.locator('.method-column.prf .result-card')).toHaveCount(5);await expect(page.locator('.method-column.human .result-card')).toHaveCount(5);await expect(page.locator('.method-column.rewrite .error-state')).toBeVisible();
 await page.locator('.raw .result-main').first().click();await expect(page.getByRole('dialog')).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);
 await page.getByRole('button',{name:'Select turn 7',exact:true}).click();await expect(page.locator('.run-info')).toContainText('Results are from older data');await expect(page.locator('.context-note')).toContainText('6 earlier turns');await page.getByLabel('Question · turn 7').fill('Should I place the secondary mesh node near the stairs?');await page.getByRole('button',{name:'Run turn 7',exact:true}).click();await expect(page.locator('.run-info')).toContainText('Turn 7 · 6 history turns');await expect(page.locator('.raw .query-box')).toContainText('Should I place the secondary mesh node');
 await page.getByRole('button',{name:'Add document',exact:true}).click();await expect(page.locator('.doc-item')).toHaveCount(11);await expect(page.getByRole('button',{name:'Run turn 7',exact:true})).toBeDisabled();await page.getByLabel('DOCUMENT TITLE',{exact:true}).fill('Custom document');await page.getByLabel('Document content',{exact:true}).fill('Place the mesh node near the stairs.\nKeep these two lines.');await page.getByRole('button',{name:'Index documents',exact:true}).click();await expect(page.getByText('Index ready',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Add turn',exact:true}).click();await expect(page.locator('.turn')).toHaveCount(11);await page.getByLabel('Question · turn 11').fill('Does the new device need a cable?');await page.getByRole('button',{name:'Move turn up',exact:true}).click();await expect(page.getByLabel('Question · turn 10')).toHaveValue('Does the new device need a cable?');await page.getByRole('button',{name:'Delete selected turn',exact:true}).click();await expect(page.locator('.turn')).toHaveCount(10);
 await page.waitForTimeout(600);await page.reload();await expect(page.locator('.doc-item')).toHaveCount(11);await expect(page.getByText('Index ready',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Custom document',exact:false}).click();await expect(page.getByLabel('Document content',{exact:true})).toHaveValue('Place the mesh node near the stairs.\nKeep these two lines.');await page.getByRole('button',{name:'Delete selected document',exact:true}).click();await expect(page.locator('.doc-item')).toHaveCount(10);
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'Export',exact:true}).click();expect((await download).suggestedFilename()).toBe('context-lab-session.json');
 expect(errors).toEqual([]);expect(requests.filter(u=>!u.startsWith('http://127.0.0.1:3000'))).toEqual([]);
});

test('rewrite receives only prefix, late responses and cancel cannot replace newer results',async({page})=>{
 let received:any;await page.route('**/api/rewrite',async route=>{if(route.request().method()==='GET'){await route.fulfill({json:{configured:true,protected:false,model:'mock',promptVersion:'test'}});return}received=route.request().postDataJSON();await new Promise(r=>setTimeout(r,600));await route.fulfill({json:{query:'Secondary mesh node placement',model:'mock',promptVersion:'test'}})});
 await page.goto('/');await page.getByRole('button',{name:'Index documents',exact:true}).click();await expect(page.getByText('Index ready',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Select turn 7',exact:true}).click();await page.getByRole('button',{name:'Run turn 7',exact:true}).click();await expect.poll(()=>received?.history.length).toBe(6);expect(Object.keys(received).sort()).toEqual(['currentQuery','history']);expect(received.history[5]).toContain('How is mesh different');await page.getByRole('button',{name:'Cancel',exact:true}).click();await page.getByRole('button',{name:'Select turn 2',exact:true}).click();await page.getByRole('button',{name:'Run turn 2',exact:true}).click();await expect(page.locator('.rewrite .result-card').first()).toBeVisible();await expect(page.locator('.run-info')).toContainText('Turn 2 · 1 history turns');expect(received.history.length).toBe(1);
});

test('mobile tabs and empty human query',async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.goto('/');await page.getByLabel('Human query OPTIONAL').fill('');await page.getByRole('button',{name:'Index documents',exact:true}).click();await expect(page.getByText('Index ready',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Run turn 3',exact:true}).click();await page.getByRole('tab',{name:'Human',exact:true}).click();await expect(page.getByText('No Human query',{exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:'test-results/mobile.png',fullPage:true});
});
