'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowDown,ArrowUp,ArrowUpRight,BookOpen,Check,ChevronRight,Download,Layers3,MessageSquare,Play,Plus,RotateCcw,Settings2,Trash2,X,LoaderCircle,PanelLeftClose,PanelLeftOpen,Search,LockKeyhole} from 'lucide-react';
import {methods,useWorkspace,type Method,type MethodResult} from '@/lib/use-workspace';
import {REWRITE_SYSTEM_PROMPT as SYSTEM_PROMPT} from '@/lib/rewrite/prompt';
import type {DemoDocument} from '@/data/demo-dataset';

const meta:Record<Method,{name:string;tag:string;description:string}>={
 raw:{name:'Raw',tag:'01',description:'Original question'},
 prf:{name:'Raw + PRF',tag:'02',description:'Expanded from feedback documents'},
 rewrite:{name:'Rewrite',tag:'03',description:'Contextual rewrite + keywords'},
 human:{name:'Human',tag:'04',description:'Reference query'}
};

function Highlight({text,terms}:{text:string;terms:string[]}){const tokens=new Set(terms.map(t=>t.toLowerCase()));return <>{text.split(/([\p{L}\p{N}]+)/u).map((part,i)=>tokens.has(part.toLowerCase())?<mark key={i}>{part}</mark>:part)}</>}
function Modal({title,children,onClose,wide=false}:{title:string;children:React.ReactNode;onClose:()=>void;wide?:boolean}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal()},[]);return <dialog ref={ref} className={wide?'modal wide':'modal'} onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose()}}><header><h2>{title}</h2><button className="icon" onClick={onClose} aria-label="Close"><X size={19}/></button></header><div className="modal-content">{children}</div></dialog>}

export default function Home(){
 const w=useWorkspace();
 const [settingsOpen,setSettingsOpen]=useState(false),[promptOpen,setPromptOpen]=useState(false),[viewer,setViewer]=useState<DemoDocument|null>(null),[highlight,setHighlight]=useState(''),[tab,setTab]=useState<Method>('raw'),[collapsed,setCollapsed]=useState(false),[password,setPassword]=useState(''),[authMessage,setAuthMessage]=useState('');
 const turnIndex=w.turns.findIndex(t=>t.id===w.selectedTurnId),turn=w.turns[turnIndex],doc=w.docs.find(d=>d.id===w.selectedDocId);const indexReady=w.indexedRevision===w.corpusRevision;const rows=[...new Set(methods.flatMap(m=>w.run?.results[m].hits.map(h=>h.id)??[]))];
 async function unlock(){try{const r=await fetch('/api/auth',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({password})});setAuthMessage(r.ok?'Rewrite unlocked.':(await r.json()).error??'Unable to unlock Rewrite.');if(r.ok)setPassword('')}catch{setAuthMessage('Could not connect to the server.')}}
 return <div className="app-shell">
 <header className="topbar"><a href="/" className="brand">Demo</a><nav><button onClick={w.restore} title="Restore sample data"><RotateCcw size={15}/><span>Restore sample</span></button><button onClick={w.exportSession}><Download size={15}/><span>Export</span></button><button className="icon settings-button" onClick={()=>setSettingsOpen(true)} aria-label="Settings"><Settings2 size={18}/></button></nav></header>
 <main><section className="intro"><div><div className="eyebrow">CONVERSATIONAL RETRIEVAL</div><h1>Comparing retrieval methods.</h1><p>Study the effect of conversational context over a shared document collection.</p></div></section>
 {w.notice&&<div role="status" className="notice">{w.notice}<button className="icon" aria-label="Dismiss notice" onClick={()=>w.setNotice('')}><X size={15}/></button></div>}
 <div className="workspace-grid">
 <section className="panel conversation-panel"><header className="panel-header"><div className="panel-title"><MessageSquare size={18}/><h2>Conversation</h2><span className="count">{w.turns.length} turns</span></div><span className="muted small">01 conversation</span></header><div className="conversation-body"><div className="turn-list" aria-label="Question turns">{w.turns.map((t,i)=><button key={t.id} className={`turn ${t.id===turn?.id?'selected':''} ${i>turnIndex?'future':''}`} onClick={()=>w.setSelectedTurnId(t.id)} aria-label={`Select turn ${i+1}`} aria-pressed={t.id===turn?.id}><span className="turn-number">{String(i+1).padStart(2,'0')}</span><span className="turn-copy">{t.text||'Untitled question'}{t.id===turn?.id&&<span className="turn-label">SELECTED QUESTION</span>}</span>{t.id===turn?.id&&<ChevronRight size={16}/>}</button>)}<button className="add-turn" onClick={w.addTurn}><Plus size={15}/>Add turn</button></div><div className="turn-editor">{turn?<><div className="field-heading"><label htmlFor="turn-text">Question · turn {turnIndex+1}</label><div className="editor-actions"><button className="icon" onClick={()=>w.moveTurn(-1)} disabled={turnIndex===0} aria-label="Move turn up"><ArrowUp size={14}/></button><button className="icon" onClick={()=>w.moveTurn(1)} disabled={turnIndex===w.turns.length-1} aria-label="Move turn down"><ArrowDown size={14}/></button><button className="icon danger" onClick={w.deleteTurn} aria-label="Delete selected turn"><Trash2 size={14}/></button></div></div><textarea id="turn-text" value={turn.text} onChange={e=>w.editTurn(turn.id,{text:e.target.value})} placeholder="Enter a plain-text question…" maxLength={4000}/>{!turn.text.trim()&&<p className="field-error">Enter a question.</p>}<div className="context-note"><Layers3 size={13}/><span>{turnIndex} earlier turns used as history · Later turns are not used</span></div><label htmlFor="human-query" className="human-label">Human query <span>OPTIONAL</span></label><textarea id="human-query" className="human-input" value={turn.humanQuery} onChange={e=>w.editTurn(turn.id,{humanQuery:e.target.value})} maxLength={8000} placeholder="Write a fully contextual query for comparison…"/></>:<div className="empty-state"><MessageSquare/><p>Conversation is empty.</p><button onClick={w.addTurn}>Add first turn</button></div>}</div></div><footer className="panel-footer"><span className="small muted">Only original questions are used as history.</span>{w.running?<button className="primary" onClick={w.cancel}><X size={15}/>Cancel</button>:<button className="primary" onClick={w.execute} disabled={!w.ready||!indexReady||w.indexing||!turn}><Play size={14} fill="currentColor"/>Run turn {turnIndex>=0?turnIndex+1:''}<span className="key-hint">→</span></button>}</footer></section>
 <section className="panel documents-panel"><header className="panel-header"><div className="panel-title"><BookOpen size={18}/><h2>Documents</h2><span className="count">{w.docs.length} docs</span></div><div className="editor-actions"><button className="text-button" onClick={w.addDoc}><Plus size={15}/>Add document</button><button className="icon" onClick={()=>setCollapsed(!collapsed)} aria-label={collapsed?'Open document panel':'Collapse document panel'}>{collapsed?<PanelLeftOpen size={16}/>:<PanelLeftClose size={16}/>}</button></div></header>{!collapsed&&<div className="documents-body"><div className="doc-list" aria-label="Document list">{w.docs.map((d,i)=><button key={d.id} className={`doc-item ${doc?.id===d.id?'selected':''}`} onClick={()=>w.setSelectedDocId(d.id)} aria-pressed={doc?.id===d.id}><span className="doc-id">{d.id.startsWith('D')&&d.id.length<5?d.id:`D${String(i+1).padStart(2,'0')}`}</span><span>{d.title||'Untitled document'}{(!d.title.trim()||!d.text.trim()||d.title.length+d.text.length>100000)&&<span className="field-error">Check document content</span>}</span>{doc?.id===d.id&&<ChevronRight size={14}/>}</button>)}{!w.docs.length&&<p className="muted empty-list">No documents yet.</p>}</div><div className="doc-editor">{doc?<><label htmlFor="doc-title">DOCUMENT TITLE</label><input id="doc-title" value={doc.title} onChange={e=>w.editDoc(doc.id,{title:e.target.value})} maxLength={500} placeholder="Set a document title…"/>{!doc.title.trim()&&<p className="field-error">A title is required.</p>}<label htmlFor="doc-text" className="sr-only">Document content</label><textarea id="doc-text" value={doc.text} onChange={e=>w.editDoc(doc.id,{text:e.target.value})} maxLength={100000} placeholder="Enter or paste plain text…"/>{!doc.text.trim()&&<p className="field-error">Content is required.</p>}<div className="doc-editor-footer"><span>{doc.text.length.toLocaleString('en-US')} characters · plain text</span><button className="icon danger" onClick={w.deleteDoc} aria-label="Delete selected document"><Trash2 size={14}/></button></div></>:<div className="empty-state"><BookOpen/><p>Add a document to build the corpus.</p><button onClick={w.addDoc}>Add document</button></div>}</div></div>}<footer className="panel-footer"><span className={`index-status ${indexReady?'ready':''}`} role="status">{w.indexing?<><LoaderCircle size={13} className="spin"/>Indexing {w.progress}%</>:indexReady?<><Check size={14}/>Index ready</>:<><span className="amber-dot"/>{w.indexedRevision===null?'No index yet':'Data changed · re-index required'}</>}</span>{w.indexing?<button className="secondary" onClick={w.cancelIndex}>Cancel indexing</button>:<button className="secondary" onClick={w.index} disabled={!w.ready||w.running}><Layers3 size={14}/>{indexReady?'Re-index':'Index documents'}</button>}</footer></section>
 </div>
 <section className="results-section"><div className="section-heading"><div><span className="eyebrow">THE EXPERIMENT</span><h2>Four retrieval methods<span className="muted">, one corpus.</span></h2></div><div className="result-controls"><label htmlFor="top-k">Show</label><select id="top-k" value={w.settings.topK} onChange={e=>w.setSettings({...w.settings,topK:Number(e.target.value) as 5|10|20})}><option value={5}>Top 5</option><option value={10}>Top 10</option><option value={20}>Top 20</option></select></div></div>
 {w.run&&<div className={`run-info ${w.stale?'stale':''}`}><span>{w.stale?'Results are from older data — ':''}Turn {w.run.turnNumber} · {w.run.history.length} history turns · Index #{w.run.corpusRevision}</span><span>{w.stale?'Run again to update':new Date(w.run.createdAt).toLocaleTimeString('en-US')}</span></div>}
 <div className="mobile-tabs" role="tablist" aria-label="Methods">{methods.map(m=><button key={m} role="tab" aria-selected={tab===m} onClick={()=>setTab(m)} className={tab===m?'active':''}>{meta[m].name}</button>)}</div>
 <div className="method-grid">{methods.map(method=><MethodColumn key={method} method={method} active={tab===method} result={w.run?.results[method]} docs={w.run?.corpus??w.docs} highlighted={highlight} onDoc={d=>{setHighlight(d.id);setViewer(d)}} onHover={setHighlight} onPrompt={()=>setPromptOpen(true)} onRetry={w.retryRewrite} retryDisabled={w.running||w.indexing||!w.run||w.run.corpusRevision!==w.indexedRevision||!indexReady} configured={!!w.config?.configured}/>)}</div>
 </section>
 <section className="panel comparison"><header className="panel-header"><div className="panel-title"><Layers3 size={17}/><h2>Rank comparison</h2></div><span className="small muted">Combined documents in top-k</span></header>{rows.length?<div className="table-scroll"><table><thead><tr><th>DOCUMENT</th>{methods.map(m=><th key={m}><span className={`method-dot ${m}`}/>{meta[m].name}</th>)}</tr></thead><tbody>{rows.map(id=>{const d=w.run?.corpus.find(d=>d.id===id);return <tr key={id} className={highlight===id?'highlighted':''} onMouseEnter={()=>setHighlight(id)} onMouseLeave={()=>setHighlight('')}><td><button onClick={()=>d&&setViewer(d)}><span className="doc-id">{id.length<8?id:'DOC'}</span>{d?.title}<ArrowUpRight size={13}/></button></td>{methods.map(m=>{const rank=w.run?.results[m].hits.findIndex(h=>h.id===id)??-1;return <td key={m}>{rank>=0?<span className={rank===0?'rank first':'rank'}>{rank+1}</span>:<span className="muted">—</span>}</td>})}</tr>})}</tbody></table></div>:<div className="comparison-empty"><Search size={19}/><p>Ranks will appear after the first run.</p></div>}<footer className="comparison-note">“—” is outside top-k. Rank describes retrieval results, not accuracy.</footer></section>
 </main>
 {viewer&&<Modal title="Full document" onClose={()=>setViewer(null)} wide><span className="eyebrow">{viewer.id.length<8?viewer.id:'DOCUMENT'} · CORPUS AT RUN</span><h2 className="viewer-title">{viewer.title}</h2><div className="document-full">{viewer.text}</div></Modal>}
 {promptOpen&&<Modal title="Rewrite with keywords · Prompt" onClose={()=>setPromptOpen(false)} wide><p className="muted">Prompt rewriter 2 from the notebook. The corpus and Human query are not sent to the LLM.</p><pre>{SYSTEM_PROMPT}</pre><h3>Run payload</h3><pre>{JSON.stringify(w.run?{history:w.run.history,currentQuery:w.run.currentQuery}:{history:[],currentQuery:''},null,2)}</pre></Modal>}
 {settingsOpen&&<Modal title="Experiment settings" onClose={()=>setSettingsOpen(false)}><div className="settings-section"><span className="eyebrow">RETRIEVAL · IN BROWSER</span><h3>MiniSearch / BM25+</h3><p className="muted">k = 1.2 · b = 0.7 · d = 0.5 · OR<br/>Preserve Unicode text. No stemming, fuzzy matching, or prefix search.</p><label>Feedback documents<input aria-label="Feedback documents" type="number" min={1} max={10} value={w.settings.feedbackDocs} onChange={e=>w.setSettings({...w.settings,feedbackDocs:Math.max(1,Math.min(10,Number(e.target.value)))})}/></label><label>Expansion terms<input aria-label="Expansion terms" type="number" min={0} max={20} value={w.settings.feedbackTerms} onChange={e=>w.setSettings({...w.settings,feedbackTerms:Math.max(0,Math.min(20,Number(e.target.value)))})}/></label><label>Expansion weight <strong>{w.settings.expansionWeight.toFixed(1)}</strong><input aria-label="Expansion weight" type="range" min={0} max={1} step={0.1} value={w.settings.expansionWeight} onChange={e=>w.setSettings({...w.settings,expansionWeight:Number(e.target.value)})}/></label><p className="small muted">PRF uses weighted TF-IDF. Set the term count or weight to 0 to keep Raw unchanged.</p></div><div className="settings-section"><span className="eyebrow">REWRITE · OLLAMA</span><h3>{w.config?.configured?w.config.model:'Ollama is not configured'}</h3><p className="muted">{w.config?.configured?'Only the history turns and current query are sent.':'Set OLLAMA_API_KEY and OLLAMA_MODEL on the server to use Rewrite. The three local methods still work.'}</p>{w.config?.protected&&<><label>Demo password<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="secondary" onClick={unlock}><LockKeyhole size={14}/>Unlock Rewrite</button><p role="status">{authMessage}</p></>}</div></Modal>}
 </div>
}

function MethodColumn({method,active,result,docs,highlighted,onDoc,onHover,onPrompt,onRetry,retryDisabled,configured}:{method:Method;active:boolean;result?:MethodResult;docs:DemoDocument[];highlighted:string;onDoc:(d:DemoDocument)=>void;onHover:(id:string)=>void;onPrompt:()=>void;onRetry:()=>void;retryDisabled:boolean;configured:boolean}){const m=meta[method];return <article className={`method-column ${method} ${active?'mobile-active':''}`}><header className="method-header"><div><span className="method-number">{m.tag}</span><h3>{m.name}</h3>{method==='rewrite'&&<span className="cloud-tag">LLM</span>}</div><p>{m.description}</p></header><div className="query-box"><div className="query-caption">ACTUAL QUERY{result?.ms!==undefined&&<span>{Math.round(result.ms)} ms</span>}</div>{result?.query?<p>{result.query}</p>:<p className="placeholder">{method==='rewrite'?'Query will be clarified from history…':method==='human'?'Reference query for the selected turn…':'Search query will appear here…'}</p>}{method==='rewrite'&&<button className="inline-link" onClick={onPrompt}>View prompt <ArrowUpRight size={12}/></button>}</div>
 {result?.trace&&<details className="trace"><summary>{result.trace.terms.length} expansion terms · {result.trace.feedbackDocIds.length} feedback docs</summary><p className="small">Feedback: {result.trace.feedbackDocIds.join(', ')||'None'}</p>{result.trace.reason&&<p>{result.trace.reason}</p>}{result.trace.terms.map(t=><div className="weight-row" key={t.term}><span>{t.term}</span><span>{t.weight.toFixed(3)}</span></div>)}</details>}
 <div className="results-list">{!result?<div className="method-empty"><span className="empty-icon"><Search size={20}/></span><strong>Ready to explore</strong><p>Index the documents, then run a question to inspect results.</p>{method==='rewrite'&&!configured&&<small>Ollama is not connected</small>}</div>:result.status==='running'?<div className="method-empty" role="status"><LoaderCircle className="spin"/><strong>{method==='rewrite'?'Clarifying context…':'Searching…'}</strong><p>{method==='rewrite'?'Local results are shown independently.':'Computed in a Web Worker.'}</p></div>:result.status==='error'?<div className="method-empty error-state"><strong>No result</strong><p>{result.error}</p></div>:result.status==='skipped'?<div className="method-empty"><strong>No Human query</strong><p>Add a reference query in the conversation panel.</p></div>:result.status==='cancelled'?<div className="method-empty"><strong>Cancelled</strong><p>Run again when ready.</p></div>:!result.hits.length?<div className="method-empty"><Search/><strong>No matching documents</strong><p>Try checking the question keywords.</p></div>:result.hits.map((hit,i)=>{const doc=docs.find(d=>d.id===hit.id);if(!doc)return null;return <div key={hit.id} className={`result-card ${highlighted===hit.id?'highlighted':''}`} onMouseEnter={()=>onHover(hit.id)} onMouseLeave={()=>onHover('')}><button className="result-main" onClick={()=>onDoc(doc)}><div className="result-topline"><span className="result-rank">{String(i+1).padStart(2,'0')}</span><span className="doc-id">{hit.id.length<8?hit.id:'DOC'}</span><ArrowUpRight size={13}/></div><h4>{doc.title}</h4><p><Highlight text={doc.text.slice(0,165)+'…'} terms={Object.keys(hit.match??{})}/></p></button><details className="score-detail"><summary>Score details</summary><span>BM25+ score: {hit.score.toFixed(4)}</span></details></div>})}</div>
 {result&&<footer className="method-footer"><span>{result.hits.length} results{result.cached?' · cache':''}</span>{method==='rewrite'&&<button className="inline-link" onClick={onRetry} disabled={retryDisabled}><RotateCcw size={12}/>Regenerate</button>}</footer>}</article>}
