'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {documents,conversation,type DemoDocument,type Turn,datasetVersion} from '@/data/demo-dataset';
import {defaultSettings,loadWorkspace,saveWorkspace,type Settings} from './storage';
import {rewrite,type RewriteResponse} from './rewrite/client';
import type {MiniSearchHit,PrfOutput} from './retrieval/engine';
import type {RetrievalWorkerRequest,RetrievalWorkerResponse} from '@/workers/retrieval.worker';
export type Method='raw'|'prf'|'rewrite'|'human';
export const methods:Method[]=['raw','prf','rewrite','human'];
export interface MethodResult {status:'running'|'success'|'error'|'skipped'|'cancelled';query:string;hits:MiniSearchHit[];ms?:number;error?:string;trace?:PrfOutput['trace'];weights?:[string,number][];provenance?:RewriteResponse;cached?:boolean}
export interface Run {id:string;turnId:string;turnNumber:number;history:string[];currentQuery:string;humanQuery:string;corpus:DemoDocument[];corpusRevision:number;conversationRevision:number;settings:Settings;createdAt:string;results:Record<Method,MethodResult>}
function uid(){return crypto.randomUUID()}
function initialResult(query:string):MethodResult{return{status:'running',query,hits:[]}}
export function validateDocuments(docs:DemoDocument[]){if(!docs.length)return 'Add at least one document before indexing.';if(docs.length>1000)return 'Maximum 1,000 documents.';if(docs.some(d=>!d.title.trim()||!d.text.trim()))return 'Every document needs a title and content.';if(docs.some(d=>d.title.length+d.text.length>100000))return 'Each document is limited to 100,000 characters.';if(new TextEncoder().encode(docs.map(d=>d.title+d.text).join('')).length>10*1024*1024)return 'The corpus exceeds 10 MB.';return ''}
export function useWorkspace(){
 const [docs,setDocs]=useState<DemoDocument[]>(documents),[turns,setTurns]=useState<Turn[]>(conversation.turns),[selectedTurnId,setSelectedTurnId]=useState('T3'),[selectedDocId,setSelectedDocId]=useState('D01');
 const [settings,setSettings]=useState<Settings>(defaultSettings),[corpusRevision,setCorpusRevision]=useState(1),[conversationRevision,setConversationRevision]=useState(1),[indexedRevision,setIndexedRevision]=useState<number|null>(null),[indexing,setIndexing]=useState(false),[progress,setProgress]=useState(0),[ready,setReady]=useState(false),[notice,setNotice]=useState(''),[run,setRun]=useState<Run|null>(null),[dirty,setDirty]=useState(false);
 const worker=useRef<Worker|null>(null),pending=useRef(new Map<string,{resolve:(x:unknown)=>void;reject:(e:Error)=>void;revision:number;start:number}>()),activeId=useRef(''),abort=useRef<AbortController|null>(null),cache=useRef(new Map<string,RewriteResponse>()),indexRequest=useRef('');
 const [config,setConfig]=useState<{configured:boolean;protected:boolean;model:string|null;promptVersion:string}|null>(null);
 useEffect(()=>{fetch('/api/rewrite').then(r=>r.json()).then(setConfig).catch(()=>{});const w=new Worker(new URL('../workers/retrieval.worker.ts',import.meta.url),{type:'module'});worker.current=w;
 w.onmessage=(event:MessageEvent<RetrievalWorkerResponse>)=>{const m=event.data,p= pending.current.get(m.requestId);if(!p||('revision'in m&&m.revision!==p.revision))return;if(m.type==='PROGRESS'){setProgress(Math.round(m.completed/Math.max(1,m.total)*100));return;}pending.current.delete(m.requestId);if(m.type==='ERROR')p.reject(new Error(m.error));else p.resolve(m.type==='RESULT'?m.result:m);};
 w.onerror=()=>{setNotice('The worker failed. Reload the page to restart it.');pending.current.forEach(p=>p.reject(new Error('Worker unavailable')));pending.current.clear()};
 let alive=true;loadWorkspace().then(saved=>{if(!alive||!saved||saved.datasetVersion!==datasetVersion)return;setDocs(saved.docs);setTurns(saved.turns);setSelectedTurnId(saved.selectedTurnId);setSelectedDocId(saved.docs[0]?.id??'');setSettings(saved.settings);setCorpusRevision(saved.corpusRevision);setConversationRevision(saved.conversationRevision);if(saved.lastRun && typeof saved.lastRun==='object' && 'results'in saved.lastRun && 'corpus'in saved.lastRun){const r=saved.lastRun as Run;for(const key of methods)if(r.results[key]?.status==='running')r.results[key].status='cancelled';setRun(r)}if(saved.wasIndexed&&!validateDocuments(saved.docs)){setIndexing(true);const requestId=uid();indexRequest.current=requestId;pending.current.set(requestId,{resolve:()=>{setIndexedRevision(saved.corpusRevision);setIndexing(false)},reject:e=>{setNotice(e.message);setIndexing(false)},revision:saved.corpusRevision,start:performance.now()});w.postMessage({type:'INDEX',requestId,revision:saved.corpusRevision,documents:saved.docs})}}).catch(()=>setNotice('Could not restore the saved session. You can continue working and export.')).finally(()=>{if(alive)setReady(true)});
 return()=>{alive=false;w.terminate();abort.current?.abort();pending.current.forEach(p=>p.reject(new Error('Worker closed')));pending.current.clear()};},[]);
 useEffect(()=>{if(!ready)return;const timeout=setTimeout(()=>{saveWorkspace({schemaVersion:1,datasetVersion,docs,turns,selectedTurnId,settings,corpusRevision,conversationRevision,wasIndexed:indexedRevision===corpusRevision,lastRun:run}).catch(()=>setNotice('Could not save in the browser. Export the session to keep your work.'))},400);return()=>clearTimeout(timeout)},[docs,turns,selectedTurnId,settings,corpusRevision,conversationRevision,indexedRevision,run,ready]);
 const request=useCallback((message:RetrievalWorkerRequest)=>new Promise<unknown>((resolve,reject)=>{if(!worker.current||message.type==='CANCEL'){reject(new Error('Worker is not ready'));return}pending.current.set(message.requestId,{resolve,reject,revision:message.revision,start:performance.now()});worker.current.postMessage(message)}),[]);
 function editDoc(id:string,patch:Partial<DemoDocument>){setDocs(old=>old.map(d=>d.id===id?{...d,...patch}:d));setCorpusRevision(r=>r+1);setDirty(true)}
 function addDoc(){const id=uid();setDocs(d=>[...d,{id,title:'',text:''}]);setSelectedDocId(id);setCorpusRevision(r=>r+1);setDirty(true)}
 function deleteDoc(){const i=docs.findIndex(d=>d.id===selectedDocId),next=docs.filter(d=>d.id!==selectedDocId);setDocs(next);setSelectedDocId(next[Math.min(i,next.length-1)]?.id??'');setCorpusRevision(r=>r+1);setDirty(true)}
 function editTurn(id:string,patch:Partial<Turn>){setTurns(old=>old.map(t=>t.id===id?{...t,...patch}:t));setConversationRevision(r=>r+1);setDirty(true)}
 function addTurn(){const id=uid();setTurns(t=>[...t,{id,text:'',humanQuery:''}]);setSelectedTurnId(id);setConversationRevision(r=>r+1);setDirty(true)}
 function deleteTurn(){const i=turns.findIndex(t=>t.id===selectedTurnId),next=turns.filter(t=>t.id!==selectedTurnId);setTurns(next);setSelectedTurnId(next[Math.min(i,next.length-1)]?.id??'');setConversationRevision(r=>r+1);setDirty(true)}
 function moveTurn(direction:number){const i=turns.findIndex(t=>t.id===selectedTurnId),j=i+direction;if(j<0||j>=turns.length)return;const next=[...turns];[next[i],next[j]]=[next[j],next[i]];setTurns(next);setConversationRevision(r=>r+1);setDirty(true)}
 const running=!!run&&methods.some(m=>run.results[m].status==='running');
 function cancel(){abort.current?.abort();const id=activeId.current;activeId.current='';for(const [key,p]of pending.current){if(key.startsWith(id+':')){worker.current?.postMessage({type:'CANCEL',requestId:key});p.reject(new Error('Cancelled'));pending.current.delete(key)}}setRun(old=>old?{...old,results:Object.fromEntries(methods.map(m=>[m,old.results[m].status==='running'?{...old.results[m],status:'cancelled'}:old.results[m]])) as Run['results']}:old)}
 async function index(){const error=validateDocuments(docs);if(error){setNotice(error);return}if(running||indexing)return;setNotice('');setIndexing(true);setProgress(0);const revision=corpusRevision;const requestId=uid();indexRequest.current=requestId;try{await request({type:'INDEX',requestId,revision,documents:docs});if(indexRequest.current===requestId)setIndexedRevision(revision)}catch(e){setNotice((e as Error).message)}finally{if(indexRequest.current===requestId)setIndexing(false)}}
 function cancelIndex(){const id=indexRequest.current;indexRequest.current='';worker.current?.postMessage({type:'CANCEL',requestId:id});pending.current.get(id)?.reject(new Error('Indexing cancelled'));pending.current.delete(id);setIndexing(false)}
 function updateResult(id:string,method:Method,value:MethodResult){if(activeId.current!==id)return;setRun(old=>old?.id===id?{...old,results:{...old.results,[method]:value}}:old)}
 async function doRewrite(snapshot:Run,force=false){const id=snapshot.id;const ctrl=new AbortController();abort.current=ctrl;const start=performance.now();try{const fresh=await fetch('/api/rewrite',{signal:ctrl.signal}).then(r=>r.json());setConfig(fresh);const key=JSON.stringify([snapshot.history,snapshot.currentQuery,fresh.model,fresh.promptVersion]);let output=!force?cache.current.get(key):undefined;const cached=!!output;if(!output){output=await rewrite({history:snapshot.history,currentQuery:snapshot.currentQuery},ctrl.signal);cache.current.set(key,output)}if(activeId.current!==id)return;const hits=await request({type:'SEARCH',requestId:`${id}:rewrite:${uid()}`,revision:snapshot.corpusRevision,query:output.query,topK:snapshot.settings.topK}) as MiniSearchHit[];updateResult(id,'rewrite',{status:'success',query:output.query,hits,ms:performance.now()-start,provenance:output,cached})}catch(e){updateResult(id,'rewrite',{status:ctrl.signal.aborted?'cancelled':'error',query:'',hits:[],error:(e as Error).message})}}
 function execute(){const i=turns.findIndex(t=>t.id===selectedTurnId);if(indexedRevision!==corpusRevision||indexing||running||i<0)return;const prefix=turns.slice(0,i+1);if(prefix.some(t=>!t.text.trim())){setNotice('The current question and every history turn must contain text.');return}if(i>50||prefix.some(t=>t.text.length>4000)||prefix.reduce((n,t)=>n+t.text.length,0)>40000){setNotice('Conversation too long: maximum 50 history turns, 4,000 characters per turn, and 40,000 characters per prefix.');return}setNotice('');const t=turns[i],id=uid();activeId.current=id;const snapshot:Run={id,turnId:t.id,turnNumber:i+1,history:turns.slice(0,i).map(t=>t.text),currentQuery:t.text,humanQuery:t.humanQuery,corpus:structuredClone(docs),corpusRevision,conversationRevision,settings:{...settings},createdAt:new Date().toISOString(),results:{raw:initialResult(t.text),prf:initialResult(t.text),rewrite:initialResult(''),human:t.humanQuery.trim()?initialResult(t.humanQuery):{status:'skipped',query:'',hits:[]}}};setRun(snapshot);
 for(const method of ['raw','prf','human'] as const){if(method==='human'&&!t.humanQuery.trim())continue;const start=performance.now(),query=method==='human'?t.humanQuery:t.text;request(method==='prf'?{type:'SEARCH_PRF',requestId:`${id}:${method}`,revision:corpusRevision,query,topK:settings.topK,settings}:{type:'SEARCH',requestId:`${id}:${method}`,revision:corpusRevision,query,topK:settings.topK}).then(value=>{const prf=method==='prf'?value as PrfOutput:null;updateResult(id,method,{status:'success',query:prf?.query??query,hits:prf?.results??value as MiniSearchHit[],ms:performance.now()-start,...(prf?{trace:prf.trace,weights:[...prf.weights]}:{})})}).catch(e=>updateResult(id,method,{status:'error',query,hits:[],error:e.message}))}void doRewrite(snapshot)}
 function retryRewrite(){if(!run||running||indexing||indexedRevision!==run.corpusRevision||indexedRevision!==corpusRevision)return;activeId.current=run.id;updateResult(run.id,'rewrite',initialResult(''));void doRewrite(run,true)}
 function restore(){if(dirty&&!window.confirm('Restoring the sample will replace unexported edits. Continue?'))return;cancel();if(indexing)cancelIndex();setDocs(structuredClone(documents));setTurns(structuredClone(conversation.turns));setSelectedTurnId('T3');setSelectedDocId('D01');setCorpusRevision(r=>r+1);setConversationRevision(r=>r+1);setRun(null);setDirty(false);setNotice('Sample restored. Click Index documents to begin.')}
 function exportSession(){const value={schemaVersion:1,datasetVersion,docs,conversation:{id:'home-wifi',turns},selectedTurnId,settings,bm25:{engine:'MiniSearch 7.2 / BM25+',k:1.2,b:0.7,d:0.5},tokenizer:'NFC Unicode letters/numbers v1',run};const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='context-lab-session.json';a.click();URL.revokeObjectURL(url);setDirty(false)}
 const stale=!!run&&(run.corpusRevision!==corpusRevision||run.conversationRevision!==conversationRevision||run.turnId!==selectedTurnId||JSON.stringify(run.settings)!==JSON.stringify(settings));
 return{docs,turns,selectedTurnId,setSelectedTurnId,selectedDocId,setSelectedDocId,settings,setSettings,corpusRevision,indexedRevision,indexing,progress,ready,notice,setNotice,run,running,stale,config,editDoc,addDoc,deleteDoc,editTurn,addTurn,deleteTurn,moveTurn,index,cancelIndex,execute,cancel,retryRewrite,restore,exportSession};
}
